"""empty message

Revision ID: 0d763eef0011
Revises: 1ffe3ba1980f
Create Date: 2022-09-14 23:55:28.865529

"""
from datetime import datetime
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d763eef0011'
down_revision = '1ffe3ba1980f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('created_at', sa.TIMESTAMP(), nullable=True, default
    =datetime.now()))
    op.add_column('venues', sa.Column('created_at', sa.TIMESTAMP(), nullable=True, default
    =datetime.now()))

    op.execute("UPDATE artists SET created_at = '2022-09-12 16:12:33' WHERE created_at IS NULL;")
    op.alter_column('artists', 'created_at', nullable=False)

    op.execute("UPDATE venues SET created_at = '2022-09-12 16:12:33' WHERE created_at IS NULL;")
    op.alter_column('venues', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'created_at')
    op.drop_column('artists', 'created_at')
    # ### end Alembic commands ###
